name: Deploy website
on:
  push:
    branches:
      - 'master'
  repository_dispatch:
    types: [source-updated]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.client_payload }}
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt-get update -qq; sudo apt-get install -y ca-certificates wget curl git rsync python3 python3-pip
      - run: wget -q -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.88.1/hugo_extended_0.88.1_Linux-64bit.deb; sudo dpkg -i /tmp/hugo.deb
      - run: pip install -r build/requirements.txt
      - run: npm install
      - name: Make the stack
        run: make all
        env:
          PRIVATE_ACCESS_TOKEN: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
          ENV: production
      - name: Run htmltest
        continue-on-error: true
        run: curl https://htmltest.wjdp.uk | bash; ./bin/htmltest -s public
      - name: Upload to AWS S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEST_DIR: ${{ secrets.AWS_S3_DIR }}
          SOURCE_DIR: 'public'
      - name: Invalidate AWS CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        with:
            DISTRIBUTION: ${{ secrets.AWS_CF_DISTRIBUTION }}
            PATHS: "/*"
            AWS_REGION: "us-east-1"
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
